language: node_js
node_js:
- 9.4.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_e88def0e67df_key -iv $encrypted_e88def0e67df_iv
  -in test_key.enc -out test_key -d
- mv test_key ~/.ssh -f
- chmod 600 ~/.ssh/test_key
after_script:
- scp -o StrictHostKeyChecking=no app.js root@47.52.104.243:/demo
